name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lines:
    runs-on: ubuntu-latest
    steps:
      - name: Generate lines metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
          plugin_lines_delay: 30
